# Generated by Django 2.0.1 on 2018-01-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Azure', 'Azure'), ('Google', 'Google'), ('Linkedin', 'Linkedin')], max_length=50)),
                ('client_id', models.CharField(max_length=50, unique=True)),
                ('client_secret', models.CharField(max_length=50, unique=True)),
                ('scope', models.TextField(max_length=2000)),
                ('token_type', models.CharField(max_length=50)),
                ('access_token', models.TextField(max_length=2000)),
                ('refresh_token', models.TextField(max_length=2000)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
    ]
